<div class="w-section about-who-section scroll-animation">
    <div class="w-container about-who-container default-paragraph">
<!--        <h1>Terms of Service</h1>-->

        <p>By using Mi Band, you agree to be bound by these Terms. If you don’t agree to these Terms, do not use Mi Band. If you are using Mi Band on behalf of an organization (such as your employer), you are agreeing to these Terms for that organization, and are indicating that you have the authority to bind that organization to these Terms. In that case, “you” and “your” will refer to that organization.</p>
        <p>We may revise the Terms from time to time. Changes may be posted to our blog and within our Apps, so please check that regularly. The most current version will always be posted on our Terms page. By continuing to use Mi Band after revisions become effective, you agree to be bound by the revised Terms. If you do not agree to the new Terms, please stop using Mi Band.</p>
        <h2>Auto Renewing Subscriptions</h2>
        For auto renewing subscriptions completed in our iOS Apps following terms apply:
        <p>
        - Payment will be charged to iTunes Account at confirmation of purchase.<br/>
        - Subscription automatically renews unless auto-renew is turned off at least 24-hours before the end of the current period.<br/>
        - Account will be charged for renewal within 24-hours prior to the end of the current period, and identify the cost of the renewal.<br/>
        - Subscriptions may be managed by the user and auto-renewal may be turned off by going to the user's Account Settings after purchase.<br/>
        - Any unused portion of a free trial period, if offered, will be forfeited when the user purchases a subscription to that publication, where applicable.<br/>
        - You can cancel a free trial or subscription anytime by turning off auto-renewal through your iTunes account settings. This must be done 24 hours before the end of a free trial or subscription period to avoid being charged. The cancellation will take effect the day after the last day of the current subscription period, and you will be downgraded to the free service.
        </p>
        <h2>Your Information and Responsibilities</h2>
        <p>To use Mi Band, you optionally can create an account, either via Mi Band or through your account with a third-party service such as Facebook. In the latter case, your Mi Band account will be created using the information you provided to that service, such as your name and email address and other personal information that your privacy settings on that service permit us to access.</p>
        <p>You may use Mi Band only if you are 13 years or older and are not barred from using Mi Band under applicable law.</p>
        <p>You are responsible for safeguarding the password that you use to access Mi Band. You are responsible for any activity on your account, whether or not you authorized that activity. You should immediately notify Mi Band of any unauthorized use of your account.</p>
        <p>By using Mi Band, you provide us with text, graphics, images and other information (“your content”). You retain full ownership to your content. Mi Band does not claim any ownership rights to your content. However, you are also solely responsible for your content. You indicate that you own or have the necessary rights to all of your content, and that use of your content does not infringe, misappropriate or violate a third party’s intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.</p>
        <h2>Mi Band Intellectual Property Rights</h2>
        <p>Mi Band and its licensors exclusively own Mi Band, including all associated intellectual property rights. You acknowledge that Mi Band is protected by copyright, trademark, and other laws of some countries. You agree not to remove, alter or obscure any copyright, trademark, service mark or other proprietary rights or notices incorporated in or accompanying Mi Band.</p>
        <p>Mi Band grants you a limited, non-exclusive, non-transferable license to view, copy, and display Mi Band solely in connection with your permitted use of Mi Band.</p>
        <h2>General Prohibitions</h2>
        <p>You agree not to do—or attempt to do—any of the following:</p>
        <ul>
            <li>Probe, scan, or test the vulnerability of any Mi Band system or network or breach any security or authentication measures;</li>
            <li>Access, tamper with, or use non-public areas of Mi Band, Mi Band’s computer systems, or the technical delivery systems of Mi Band’s providers;</li>
            <li>Decipher, decompile, disassemble or reverse engineer any of the software used to provide Mi Band;</li>
            <li>Interfere with, or attempt to interfere with, the access of any user, host or network, including sending a virus, overloading, flooding, spamming, or mail-bombing Mi Band;</li>
            <li>Access or search Mi Band or download any intellectual property from Mi Band through the use of any engine, software, tool, agent, device or mechanism (including spiders, robots, crawlers, data mining tools or the like) other than our publicly supported interfaces;</li>
            <li>Plant malware or use Mi Band to distribute malware;</li>
            <li>Send any unsolicited communications, promotions, advertisements or spam;</li>
            <li>Send altered, deceptive or false source-identifying information, including “spoofing” or “phishing”;</li>
            <li>Post or transmit anything that is fraudulent or misleading, or that infringes on others' rights;</li>
            <li>Impersonate or misrepresent your affiliation with any person or entity;</li>
            <li>Violate the privacy of others;</li>
            <li>Violate any applicable law or regulation; or</li>
            <li>Encourage or enable any other individual to do any of the above.</li>
        </ul>
        <p>Although we’re not obligated to monitor access to or use of Mi Band or your content or to review or edit any of your content or the intellectual property of other Mi Band users, we have the right to do so for the purpose of operating Mi Band, to ensure compliance with these Terms, or to comply with applicable law or other legal requirements. We reserve the right, but are not obligated, to remove or disable access to any of your content, at any time and without notice, including, but not limited to, if we, at our sole discretion, consider any of your content to be objectionable or in violation of these Terms. We have the right to investigate violations of these Terms or conduct that affects Mi Band. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.</p>
        <h2>DMCA/Copyright Policy</h2>
        <p>We respect copyright law and expect you to do the same. It's our policy to terminate those accounts that repeatedly infringe or are believed to be repeatedly infringing the rights of copyright holders.</p>
        <h2>Termination</h2>
        <p>We may suspend Mi Band or terminate your access to and use of Mi Band, at our sole discretion, at any time and without notice to you. For example, we may suspend or terminate your use if you are not complying with these Terms, or use Mi Band in any way that would cause us legal liability or disrupt others’ use of Mi Band. If we suspend or terminate your use, we will try to let you know in advance and help you retrieve data, though there may be some cases (for example, repeatedly or flagrantly violating these Terms, a court order, or danger to other users) where we may suspend immediately. You may cancel your account at any time by sending an email to <a href="mailto:ankita.caet12@gmail.com">ankita.caet12@gmail.com</a>.</p>
        <h2>Warranty Disclaimers</h2>
        <p>Mi Band OR OUR LICENSORS' INTELLECTUAL PROPERTY ARE PROVIDED “AS IS,” WITHOUT WARRANTY OF ANY KIND. WITHOUT LIMITING THE FOREGOING, WE EXPLICITLY DISCLAIM ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT AND NON-INFRINGEMENT AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. WE MAKE NO WARRANTY THAT Mi Band WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. WE MAKE NO WARRANTY REGARDING THE QUALITY, ACCURACY, TIMELINESS, TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF ANY OF OUR INTELLECTUAL PROPERTY.</p>
        <h2>Indemnity</h2>
        <p>You will indemnify and hold harmless Mi Band and its officers, directors, employees and agents, from and against any claims, disputes, demands, liabilities, damages, losses, and costs and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with (i) your access to or use of Mi Band or our licensors' intellectual property; (ii) your content; or (iii) your violation of these Terms.</p>
        <h2>Limitation of Liability</h2>
        <p>NEITHER Mi Band NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING Mi Band, INCLUDING OUR LICENSORS, WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE SERVICES ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE Mi Band OR OUR LICENSORS' INTELLECTUAL PROPERTY, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT Mi Band HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
        <p>IN NO EVENT WILL Mi Band’S TOTAL LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE Mi Band OR TO ACCESS YOUR CONTENT EXCEED THE AMOUNTS YOU HAVE PAID TO Mi Band FOR USE OF Mi Band OR TWENTY DOLLARS ($20), IF YOU HAVE NOT HAD ANY PAYMENT OBLIGATIONS TO Mi Band, AS APPLICABLE. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN Mi Band AND YOU.</p>
        <h2>GOVERNING LAW</h2>
        <p>These Terms and any action related thereto will be governed by the laws of the Austria without regard to its conflict of laws provisions.</p>
        <h2>General Terms</h2>
        <p>These Terms constitute the entire and exclusive understanding and agreement between Mi Band and you regarding Mi Band, and these Terms supersede and replace any and all prior oral or written understandings or agreements between Mi Band and you regarding Mi Band, except that if you become a party to Mi Band's Business Agreement, either before or after reviewing these Terms, the terms and conditions of the Business Agreement will govern over any conflicting provisions herein. If for any reason a court of competent jurisdiction finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.</p>
        <p>You may not assign or transfer these Terms, by operation of law or otherwise, without Mi Band’s prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, will be null and of no effect. Mi Band may freely assign or transfer these Terms without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.</p>
        <p>Any notices or other communications provided by Mi Band under these Terms, including those regarding modifications to these Terms, will be given: (i) by Mi Band via email; or (ii) by posting to our website. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.</p>
        <p>Mi Band’s failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of Mi Band. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise.</p>

    </div>
</div></div>
