<div class="w-section about-who-section scroll-animation">
    <div class="w-container about-who-container default-paragraph">
<!--        <h1>Terms of Service</h1>-->
<p>Thank you for using WalknEarn. WalknEarn is operated by Hexalab Software Pvt Ltd., a cooperation based in Bangalore, India. These Terms of Service (the &acirc;&euro;&oelig;Terms&acirc;&euro;) govern your use of all available WalknEarn Services and Apps (&acirc;&euro;&oelig;WalknEarn&acirc;&euro;), so please read them carefully before using WalknEarn.</p>
<p>By using WalknEarn, you agree to be bound by these Terms. If you don&acirc;&euro;&trade;t agree to these Terms, do not use WalknEarn. If you are using WalknEarn on behalf of an organization (such as your employer), you are agreeing to these Terms for that organization, and are indicating that you have the authority to bind that organization to these Terms. In that case, &acirc;&euro;&oelig;you&acirc;&euro; and &acirc;&euro;&oelig;your&acirc;&euro; will refer to that organization.</p>
<p>We may revise the Terms from time to time. Changes may be posted to our blog and within our Apps, so please check that regularly. The most current version will always be posted on our Terms page. By continuing to use WalknEarn after revisions become effective, you agree to be bound by the revised Terms. If you do not agree to the new Terms, please stop using WalknEarn.</p>
<p><span style="text-decoration: underline;"><strong>Your Information and Responsibilities</strong></span><br />To use WalknEarn, you optionally can create an account, either via WalknEarn or through your account with a third-party service such as Facebook. In the latter case, your WalknEarn account will be created using the information you provided to that service, such as your name and email address and other personal information that your privacy settings on that service permit us to access.</p>
<p>You may use WalknEarn only if you are 13 years or older and are not barred from using WalknEarn under applicable law.</p>
<p>You are responsible for safeguarding the password that you use to access WalknEarn. You are responsible for any activity on your account, whether or not you authorized that activity. You should immediately notify WalknEarn of any unauthorized use of your account.</p>
<p>By using WalknEarn, you provide us with text, graphics, images and other information (&acirc;&euro;&oelig;your content&acirc;&euro;). You retain full ownership to your content. WalknEarn does not claim any ownership rights to your content. However, you are also solely responsible for your content. You indicate that you own or have the necessary rights to all of your content, and that use of your content does not infringe, misappropriate or violate a third party&acirc;&euro;&trade;s intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.</p>
<p>WalknEarn Intellectual Property Rights<br />WalknEarn and its licensors exclusively own WalknEarn, including all associated intellectual property rights. You acknowledge that WalknEarn is protected by copyright, trademark, and other laws of some countries. You agree not to remove, alter or obscure any copyright, trademark, service mark or other proprietary rights or notices incorporated in or accompanying WalknEarn.</p>
<p>WalknEarn grants you a limited, non-exclusive, non-transferable license to view, copy, and display WalknEarn solely in connection with your permitted use of WalknEarn.</p>
<p><span style="text-decoration: underline;"><strong>General Prohibitions</strong></span><br />You agree not to do&acirc;&euro;&rdquo;or attempt to do&acirc;&euro;&rdquo;any of the following:</p>
<p>Probe, scan, or test the vulnerability of any WalknEarn system or network or breach any security or authentication measures;<br />Access, tamper with, or use non-public areas of WalknEarn, WalknEarn&acirc;&euro;&trade;s computer systems, or the technical delivery systems of WalknEarn&acirc;&euro;&trade;s providers;<br />Decipher, decompile, disassemble or reverse engineer any of the software used to provide WalknEarn;<br />Interfere with, or attempt to interfere with, the access of any user, host or network, including sending a virus, overloading, flooding, spamming, or mail-bombing WalknEarn;<br />Access or search WalknEarn or download any intellectual property from WalknEarn through the use of any engine, software, tool, agent, device or mechanism (including spiders, robots, crawlers, data mining tools or the like) other than our publicly supported interfaces;<br />Plant malware or use WalknEarn to distribute malware;<br />Send any unsolicited communications, promotions, advertisements or spam;<br />Send altered, deceptive or false source-identifying information, including &acirc;&euro;&oelig;spoofing&acirc;&euro; or &acirc;&euro;&oelig;phishing&acirc;&euro;;<br />Post or transmit anything that is fraudulent or misleading, or that infringes on others' rights;<br />Impersonate or misrepresent your affiliation with any person or entity;<br />Violate the privacy of others;<br />Violate any applicable law or regulation; or<br />Encourage or enable any other individual to do any of the above.<br />Although we&acirc;&euro;&trade;re not obligated to monitor access to or use of WalknEarn or your content or to review or edit any of your content or the intellectual property of other WalknEarn users, we have the right to do so for the purpose of operating WalknEarn, to ensure compliance with these Terms, or to comply with applicable law or other legal requirements. We reserve the right, but are not obligated, to remove or disable access to any of your content, at any time and without notice, including, but not limited to, if we, at our sole discretion, consider any of your content to be objectionable or in violation of these Terms. We have the right to investigate violations of these Terms or conduct that affects WalknEarn. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.</p>
<p><span style="text-decoration: underline;"><strong>DMCA/Copyright Policy</strong></span><br />We respect copyright law and expect you to do the same. It's our policy to terminate those accounts that repeatedly infringe or are believed to be repeatedly infringing the rights of copyright holders.</p>
<p><span style="text-decoration: underline;"><strong>Termination</strong></span><br />We may suspend WalknEarn or terminate your access to and use of WalknEarn, at our sole discretion, at any time and without notice to you. For example, we may suspend or terminate your use if you are not complying with these Terms, or use WalknEarn in any way that would cause us legal liability or disrupt others&acirc;&euro;&trade; use of WalknEarn. If we suspend or terminate your use, we will try to let you know in advance and help you retrieve data, though there may be some cases (for example, repeatedly or flagrantly violating these Terms, a court order, or danger to other users) where we may suspend immediately. You may cancel your account at any time by sending an email to WalknEarn.walknearn2019@gmail.com.</p>
<p><span style="text-decoration: underline;"><strong>Warranty Disclaimers</strong></span><br />WalknEarn OR OUR LICENSORS' INTELLECTUAL PROPERTY ARE PROVIDED &acirc;&euro;&oelig;AS IS,&acirc;&euro; WITHOUT WARRANTY OF ANY KIND. WITHOUT LIMITING THE FOREGOING, WE EXPLICITLY DISCLAIM ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT AND NON-INFRINGEMENT AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. WE MAKE NO WARRANTY THAT WalknEarn WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. WE MAKE NO WARRANTY REGARDING THE QUALITY, ACCURACY, TIMELINESS, TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF ANY OF OUR INTELLECTUAL PROPERTY.</p>
<p><span style="text-decoration: underline;"><strong>Indemnity</strong></span><br />You will indemnify and hold harmless WalknEarn and its officers, directors, employees and agents, from and against any claims, disputes, demands, liabilities, damages, losses, and costs and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with (i) your access to or use of WalknEarn or our licensors' intellectual property; (ii) your content; or (iii) your violation of these Terms.</p>
<p><span style="text-decoration: underline;"><strong>Limitation of Liability</strong></span><br />NEITHER WalknEarn NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING WalknEarn, INCLUDING OUR LICENSORS, WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE SERVICES ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE WalknEarn OR OUR LICENSORS' INTELLECTUAL PROPERTY, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT WalknEarn HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</p>
<p>IN NO EVENT WILL WalknEarn&acirc;&euro;&trade;S TOTAL LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE WalknEarn OR TO ACCESS YOUR CONTENT EXCEED THE AMOUNTS YOU HAVE PAID TO WalknEarn FOR USE OF WalknEarn OR TWENTY DOLLARS ($20), IF YOU HAVE NOT HAD ANY PAYMENT OBLIGATIONS TO WalknEarn, AS APPLICABLE. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN WalknEarn AND YOU.</p>
<p><span style="text-decoration: underline;"><strong>GOVERNING LAW</strong></span><br />These Terms and any action related thereto will be governed by the laws of the Austria without regard to its conflict of laws provisions.</p>
<p><span style="text-decoration: underline;"><strong>General Terms</strong></span><br />These Terms constitute the entire and exclusive understanding and agreement between WalknEarn and you regarding WalknEarn, and these Terms supersede and replace any and all prior oral or written understandings or agreements between WalknEarn and you regarding WalknEarn, except that if you become a party to WalknEarn's Business Agreement, either before or after reviewing these Terms, the terms and conditions of the Business Agreement will govern over any conflicting provisions herein. If for any reason a court of competent jurisdiction finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.</p>
<p>You may not assign or transfer these Terms, by operation of law or otherwise, without WalknEarn&acirc;&euro;&trade;s prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, will be null and of no effect. WalknEarn may freely assign or transfer these Terms without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.</p>
<p>Any notices or other communications provided by WalknEarn under these Terms, including those regarding modifications to these Terms, will be given: (i) by WalknEarn via email; or (ii) by posting to our website. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.</p>
<p>WalknEarn&acirc;&euro;&trade;s failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of WalknEarn. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise.</p>
<p><span style="text-decoration: underline;"><strong>Contact Information</strong></span><br />If you have any questions about these Terms, please contact us at walkearn2019@gmail.com</p>

    </div>
</div></div>
